name: 'test-python-and-clone'

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**.md'
      - '!readme.md'
      - '!**.gitignore'

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  checks: write
  deployments: write
  packages: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Markdown2Html:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run build.py
        run: |
          ls
          python -m pip install --upgrade pip
          pip install markdown2
          python build.py
      - name: Commit
        run: |
          git config --global user.email dongfangbubaijcs@gmail.com
          git config --global user.name dfbb1
          git add .
          git commit -m"action:`date`"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1