name: 'test-python-and-clone'

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**.md'

jobs:
  Python-Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run test.py
        run: |
          echo "print('hello, python is running')" > test.py
          python -m pip install --upgrade pip
          pip install markdown2
          python test.py
